### PR TITLE
.NET Standard migration

### PR DESCRIPTION
**Pull request by EdgarSalazar**
I wanted to pack the project to a Nuget package so I could easily use it in others projects. I had to upgrade the framework to .NET Standard for it to work.

Had to migrate the `container-packing.html` to a dotnet core MVC app. All of it's implementation is in the `Index.cshtml` and should be rendered as the initial page when you run `dotnet run`.

Nuget package: https://www.nuget.org/packages/CromulentBisgetti.ContainerPacking/

Also, I updated the README with a URL to demo being hosted on one of my hosting: https://containerpacking.moniapp.a2hosted.com/ (I'll try to keep it online always, not 100% guaranteed)

### CODE REVIEW

**Comment by davidmchapman** [comment]
Thank you, Edgar! I had wanted to port this to Standard, so this is great. I'm going to try to review these within the next few days, as my schedule allows.

**Comment by EdgarSalazar** [comment]
I'm pretty sure you're a very busy man. Thanks!

Em qui, 1 de nov de 2018 22:37, davidmchapman <notifications@github.com
escreveu:

**Comment by EdgarSalazar** [comment]
It uses dotnet core. Can I assist you in any way?

**Comment by palodequeso** [comment]
Ooh, you upgraded this whole thing to .net core? You're my hero.

**Comment by davidmchapman** [comment]
We're gettin there! Haha. Nuget was a local feed issue. Just resolved it. Testing now...

**Comment by EdgarSalazar** [comment]
@palodequeso  Yep, I did it.

**Comment by palodequeso** [comment]
I ported dvdoug's boxpacker to C# a while ago, but it's internal company use only. I'm not able to open source it yet, but this looks like it's better anyway. :)

**Comment by EdgarSalazar** [comment]
@palodequeso this lib is good to the point you can simply implement new algorithms into it, so maybe you could just box-in dvdoug's algorithm logic to a new class and add it to the enum, and modify tests, and it should work just fine.

**Comment by davidmchapman** [comment]
@EdgarSalazar it looks like the sln file has a new reference to Demo.csproj. Looks like that reference should be removed? I don't see that file in src.

**Comment by EdgarSalazar** [comment]
@davidmchapman checking

**Comment by EdgarSalazar** [comment]
I see, just found the issue. Project was unloaded here, from when I was migrating the folders. Will push a fix now.

**Comment by EdgarSalazar** [comment]
Fixed.

**Comment by davidmchapman** [comment]
Awesome. I think my only concern is that perhaps the link to the live demo should state that the demo is hosted by you. That way it is clear to users that they are navigating away from this repo. (In other words, that there is no implied connection between the repo and the hosted app.) Does that make sense?

**Comment by EdgarSalazar** [comment]
Absolutely, couldn't agree more. Will commit in a few minutes. The message will be:

Demo hosted by user @edgarsalazar, and not maintained nor endorsed by this project's owner.

**Comment by davidmchapman** [comment]
Perfect! And all 700 packing tests passed, so we are good to go after that change.

**Comment by EdgarSalazar** [comment]
Will do CI on future, just so the project get published on my hosting automatically.

**Comment by davidmchapman** [comment]
Thanks again for this! Much appreciated.

**Comment by EdgarSalazar** [comment]
Mr. @davidchapman , do you have Nuget account? I would like to add you as one of the Nuget Package owners: https://www.nuget.org/packages/CromulentBisgetti.ContainerPacking/1.0.0

**Comment by davidmchapman** [comment]
Now I do! My nuget name is davidmchapman
Does that give you what you need?
(Thanks!)

**Comment by EdgarSalazar** [comment]
Yep, owner request is pending your approval.

Em qua, 14 de nov de 2018 00:59, davidmchapman <notifications@github.com
escreveu:

**Pull request merged**
